---
title: "SFEI Data Wrangling"
author: "Skyler Elmstrom"
date: "12/18/2020"
output:
  html_document:
    code_folding: show
    code_download: true
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(data.table)
library(here)
library(sf)
library(plyr)
library(tidyverse)
library(knitr)
```

```{r}
# Add SFEI Data Tables
SFEI.loc <- read.csv("Data/SFEI_MicroparticleData_2020SEP08_locations.csv", fileEncoding="UTF-8-BOM") %>%
  select(-OBJECTID) %>%
  rename(StationCode = StationID)
SFEI.fish <- read.csv("Data/SFEI_MicroparticleData_2020SEP08_fish.csv", fileEncoding="UTF-8-BOM")
SFEI.eff <- read.csv("Data/SFEI_MicroparticleData_2020SEP08_eff.csv", fileEncoding="UTF-8-BOM")
SFEI.manta <- read.csv("Data/SFEI_MicroparticleData_2020SEP08_manta.csv", fileEncoding="UTF-8-BOM")
SFEI.sw <- read.csv("Data/SFEI_MicroparticleData_2020SEP08_sw.csv", fileEncoding="UTF-8-BOM")
SFEI.sed <- read.csv("Data/SFEI_MicroparticleData_2020SEP08_sed.csv", fileEncoding="UTF-8-BOM")
SFEI.particles <- read.csv("Data/SFEI_MicroparticleData_2020SEP08_Particles.csv", fileEncoding="UTF-8-BOM")
SFEI.manta <- read.csv("Data/SFEI_MicroparticleData_2020SEP18_MantaFullCoordinates.csv", fileEncoding="UTF-8-BOM")
```

```{r}
SFEI.StationTables <- list(SFEI.eff, SFEI.fish, SFEI.manta, SFEI.sed, SFEI.sw)

# https://stackoverflow.com/questions/43938863/dplyr-filter-with-condition-on-multiple-columns
SFEI.ID.Table <- rbindlist(SFEI.StationTables, use.names=T, fill=T)
SFEI.ID.Table <- SFEI.ID.Table %>%
  filter(!SampleID=="") %>% # remove empty rows
  filter(!SampleID %like% "Blank", !SampleTypeCode %like% "Blank") %>% # remove all blank rows
  select(intersect( colnames(SFEI.sw),  colnames(SFEI.eff)),
         -contains("Collection"),
         -c(ProjectCode, EventCode, LocationCode, GeometryShape, PositionWaterColumn, SampleTypeCode))

# Join Tables
SFEI.ID.loc <- left_join(SFEI.ID.Table, SFEI.loc, by = "StationCode")
SFEI.ID.particles <- left_join(SFEI.particles, SFEI.ID.loc, by = "SampleID") %>%
  filter(!SampleID %like% "Blank", !SampleID %like% "blank") %>% # remove all blank rows
  filter(!is.na(Latitude)) # removes values with no lat/long

# Convert Tables to sf
SFEI.ID.particles.sf <- st_as_sf(SFEI.ID.particles, coords = c("Longitude", "Latitude"), crs = "WGS84")

# Load Shapefiles
SFB.riskregions <- st_read("Data/SFB_RiskRegions_Prelim20AUG2020.shp") %>% # transforms shapefile CRS to WGS84 vs NAD83
  st_transform(st_crs(SFEI.ID.particles.sf))

ggplot() +
  geom_sf(data = SFB.riskregions) +
  geom_sf(data = SFEI.ID.particles.sf, color = "orange")
```



